#!/usr/bin/env bash
if [ "${BASH_VERSINFO[0]}" -lt 5 ]; then
	>& 2 echo -e "You are running an old version of Bash: $BASH_VERSION\nConsider upgrading to version 5 or later\n"
fi
set -o errexit
set -o noclobber
set -o nounset
set -o pipefail

function install() {
	declare -rix EXIT_FAILURE=1
	declare -rix EXIT_SUCCESS=0
	declare -ix return_value=$EXIT_FAILURE
	if [ $# -lt 3 ] || [ ! -d "$1" ]; then
		>& 2 echo "Usage: $(basename "$0") SRC-DIR DEST-DIR FILE..."
	else
		declare -rx src_dir="$(realpath "$1")"
		declare -rx dest_dir="$2"
		if [ ! -d "$dest_dir" ]; then
			mkdir --parents "$dest_dir"
		fi
		shift 2
		declare -arx files=("$@")
		return_value=$EXIT_SUCCESS
		for file in "${files[@]}"; do
			if [ ! -f "$src_dir/$file" ]; then
				>& 2 echo "Source file not found: $src_dir/$file"
				return_value=$EXIT_FAILURE
			fi
		done
		if [ $return_value -eq $EXIT_SUCCESS ]; then
			for file in "${files[@]}"; do
				declare -rx target="$dest_dir/$file"
				if [ -h "$target" ]; then
					unlink "$target"
				fi
				ln --symbolic "$src_dir/$file" "$target"
			done
		fi
	fi
	return $return_value
}

install "$(dirname "${BASH_SOURCE[0]}")/bin" "$HOME/bin" keygen
