#!/usr/bin/env bash
if [ "${BASH_VERSINFO[0]}" -lt 5 ]; then
	>& 2 printf 'You are running an old version of Bash: %s\nConsider upgrading to version 5 or later\n' "$(tput rev)$BASH_VERSION$(tput sgr0)"
fi
set -o errexit
set -o noclobber
set -o nounset
set -o pipefail

function install() {
	declare -ir EXIT_FAILURE=1
	declare -ir EXIT_SUCCESS=0
	declare -i return_value=$EXIT_FAILURE
	if [ $# -lt 3 ] || [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ ! -d "$1" ]; then
		>& 2 printf 'Usage: %s SRC-DIR DEST-DIR FILE...\n' "$(basename "${BASH_SOURCE[0]}")"
	else
		declare -r src_dir="$(realpath "$1")"
		declare -r dest_dir="$2"
		if [ ! -d "$dest_dir" ]; then
			mkdir -m 0700 -p "$dest_dir"
		fi
		shift 2
		declare -ar files=("$@")
		return_value=$EXIT_SUCCESS
		for file in "${files[@]}"; do
			if [ ! -f "$src_dir/$file" ]; then
				>& 2 printf 'Source file not found: %s\n' "$(tput rev)$src_dir/$file$(tput sgr0)"
				return_value=$EXIT_FAILURE
			fi
		done
		if [ $return_value -eq $EXIT_SUCCESS ]; then
			for file in "${files[@]}"; do
				declare -r target="$dest_dir/$file"
				if [ -h "$target" ]; then
					unlink "$target"
				fi
				ln -s "$src_dir/$file" "$target"
			done
		fi
	fi
	return $return_value
}

install "$(dirname "${BASH_SOURCE[0]}")/bin" "$HOME/bin" keygen
