#!/usr/bin/env bash
set -euo pipefail

function keygen() {
	declare -rix EXIT_FAILURE=1
	declare -rix EXIT_SUCCESS=0
	if [ $# -ne 1 ]; then
		>& 2 echo "Usage: $0 USER"
		return $EXIT_FAILURE
	else
		declare -rx user="$1"
		declare -rx prefix="$HOME/.ssh/keys/${user}_ed25519_"
		declare -rx suffix=_OpenSSH
		ssh-keygen -vvv -t ed25519 -a 100 -N '' -C "$user" -f "${prefix}private$suffix"
		mv "$prefix"{"private$suffix.pub","public$suffix"}
		return $EXIT_SUCCESS
	fi
}

keygen "$@"
